### PR TITLE
Update mkldnn link and fix syntaxwarning

### PR DESCRIPTION
**Pull request by wkcn**
Hi there,
In this PR, there are two tiny changes.

1. Update the link of MKLDNN
The new link of MKLDNN is https://github.com/oneapi-src/oneDNN
2. Fix the SyntaxWarning about `is` and `is not`.
When importing megengine in the first time in Python 3.8, it will raise the following warning:
```
/home/wkcn/proj/megengine/build/python_module/megengine/_internal/craniotome.py:311: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cur is 0:
/home/wkcn/proj/megengine/build/python_module/megengine/core/function.py:49: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if isinstance(grads, Tensor) or grads is None or grads is 0:
/home/wkcn/proj/megengine/build/python_module/megengine/core/function.py:58: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  list(x._symvar if x is not None and x is not 0 else 0 for x in grads)
```

### CODE REVIEW

**Comment by windreamer** [comment]
You may need to modify the [ACKNOWLEDGMENTS](https://github.com/MegEngine/MegEngine/blob/master/ACKNOWLEDGMENTS) file at the same time.

**Comment by wkcn** [comment]
Hi @windreamer , I have updated the ACKNOWLEDGMENT.

**Comment by xxr3376** [comment]
@wkcn Please provide a better commit message, and try to put different changes into two commit, thx.

We prefer [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by wkcn** [comment]
@xxr3376 Thank you! I will organize them later.

**Comment by wkcn** [comment]
Close it and re-commit two PRs : )

**Pull request closed without merging**
